---

- name: manage pools
  include_tasks: pool.yml
  loop: "{{ pools }}"
  loop_control:
    loop_var: pool

- name: manage volumes
  include_tasks: volume.yml
  loop: "{{ volumes }}"
  loop_control:
    loop_var: volume
