---
- name: Stat the final device file
  include_tasks: stat_device.yml

- name: set path-based device identifier to be used in /etc/fstab
  set_fact:
    mount_device_id: "{{ device_path }}"

- block:
    - name: collect file system UUID
      command: blkid -s UUID -o value {{ device_path }}
      register: blkid_output
      changed_when: false
    - name: set uuid-based device identifier to be used in /etc/fstab
      set_fact:
        mount_device_id: "UUID=\"{{ blkid_output.stdout }}\""
  rescue:
    - debug:
        msg: "Failed to get UUID for {{ device_path }}; trying with device path."
  when: volume.mount_device_identifier == "uuid" and device_status.stat.exists and not ansible_check_mode

#
# Activate configured mounts.
#
- name: configure mount state (1/2)
  set_fact:
    mount_state: "{{ volume.state if volume.state == 'absent' else 'mounted' }}"

- name: configure mount state (2/2)
  set_fact:
    mount_state: "{{ pool.state }}"
  when: pool.state is defined and pool.state == "absent"

# Set up the mount using a stable device identifier.
- name: Set up the mount
  mount:
    src: "{{ mount_device_id }}"
    path: "{{ volume.mount_point }}"
    fstype: "{{ volume.fs_type }}"
    opts: "{{ volume.mount_options }}"
    state: "{{ mount_state }}"
  when: volume.mount_point and device_path
