---

# TODO: Figure out how to get the name of the new partition.
# TODO: Figure out how to determine partition disk(s) and size(s).
#
# state
#   present when
#     volume.type == 'partition'
#     use_partitions and volume.type != 'disk'
- name: manage partition as needed
  parted:
    device: "{{ volume.disks[0] if volume is defined and volume.type|default == 'partition' else disk }}"
    label: "{{ disklabel_type }}"
    number: 1
    name: "{{ volume.name|default if volume is defined else pool.name|default }}"
    state: "{{ volume.state if (volume is defined and volume.type|default == 'partition') else pool.state if (use_partitions and pool is defined and pool.type|default('none') != 'disk') }}"
  register: part_info
  when: (disk is defined and use_partitions) or (volume is defined and volume.type is defined and volume.type == 'partition')

- debug:
    var: part_info
